export type FundingType =
  | "accelerator"
  | "fellowship"
  | "studio"
  | "fund-program"
  | "grant"
  | "residency"
  | "competition"
  | "government";

export type Stage = "pre-idea" | "pre-seed" | "seed" | "series-a" | "any";

export type Opportunity = {
  slug: string;
  name: string;
  type: FundingType;
  stage: Stage[];
  amount: string;
  terms: string;
  location: string;
  focus: string;
  deadline: string;
  applyUrl: string;
  website: string;
  requirements: string[];
  timeEstimate: string;
  tags: string[];
  contact?: string;
};

export const FUNDING: Opportunity[] = [
  // ---------- Top accelerators ----------
  {
    slug: "yc",
    name: "Y Combinator",
    type: "accelerator",
    stage: ["pre-idea", "pre-seed", "seed"],
    amount: "$500K ($125K SAFE + $375K MFN)",
    terms: "7% equity + uncapped SAFE",
    location: "Mountain View · 3 months in person",
    focus: "Any ambitious startup; heavy AI bias right now",
    deadline: "Batches in Winter/Spring/Summer/Fall, rolling",
    applyUrl: "https://ycombinator.com/apply",
    website: "https://ycombinator.com",
    requirements: [
      "Written app: company, idea, progress, team, why you",
      "60-second founder video (laptop cam)",
      "Links to demo / product / GitHub",
      "Co-founder breakdown + equity",
    ],
    timeEstimate: "3–6h (written) + 2–4h video & links + 10-min interview",
    tags: ["ai", "engineer", "founder", "technical", "generalist"],
  },
  {
    slug: "spc",
    name: "South Park Commons",
    type: "fellowship",
    stage: ["pre-idea", "pre-seed"],
    amount: "$400K (Founder Fellowship) · $1M+ (SPC Fund)",
    terms: "Community + capital, terms negotiated",
    location: "SF, NYC, London",
    focus: "Pre-idea technical founders / researchers",
    deadline: "Rolling",
    applyUrl: "https://southparkcommons.com/apply",
    website: "https://southparkcommons.com",
    requirements: [
      "Short written application",
      "Area of exploration + unfair advantage",
      "References from community members help",
    ],
    timeEstimate: "2–3h",
    tags: ["pre-idea", "technical", "founder", "research", "ai"],
  },
  {
    slug: "a16z-speedrun",
    name: "a16z Speedrun",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$1M",
    terms: "Standard terms, ~12-week program",
    location: "San Francisco",
    focus: "Games × tech (now also AI/consumer)",
    deadline: "Batches ~3x/yr",
    applyUrl: "https://a16z.com/games/speedrun/",
    website: "https://a16z.com/games/speedrun/",
    requirements: [
      "Pitch deck",
      "Team backgrounds + shipping record",
      "Demo if possible",
    ],
    timeEstimate: "3–5h",
    tags: ["games", "ai", "consumer", "founder"],
  },
  {
    slug: "a16z-txo",
    name: "a16z Talent x Opportunity (TxO)",
    type: "fund-program",
    stage: ["pre-seed", "seed"],
    amount: "$175K",
    terms: "SAFE + ~12 mo support",
    location: "Remote",
    focus: "Founders from overlooked backgrounds",
    deadline: "Cohorts annually",
    applyUrl: "https://a16z.com/txo/",
    website: "https://a16z.com/txo/",
    requirements: ["App + team story", "Product or early traction"],
    timeEstimate: "3–4h",
    tags: ["founder", "equity", "diversity"],
  },
  {
    slug: "500global",
    name: "500 Global Flagship",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$150K",
    terms: "6% equity, 4-month program",
    location: "San Francisco / global",
    focus: "Early-stage, global",
    deadline: "Rolling cohorts",
    applyUrl: "https://500.co/accelerators",
    website: "https://500.co",
    requirements: ["Pitch deck", "Product demo"],
    timeEstimate: "3–4h",
    tags: ["founder", "global", "generalist"],
  },
  {
    slug: "antler",
    name: "Antler",
    type: "accelerator",
    stage: ["pre-idea", "pre-seed"],
    amount: "$100K–250K (varies by geo)",
    terms: "~10% equity",
    location: "30+ cities globally",
    focus: "Pre-idea: come for cofounder matching + first check",
    deadline: "Rolling; programs start every few months",
    applyUrl: "https://antler.co/apply",
    website: "https://antler.co",
    requirements: [
      "Background + skills",
      "Ideas you're exploring",
      "Video intro + interview",
    ],
    timeEstimate: "2–3h + interviews",
    tags: ["pre-idea", "founder", "generalist"],
  },
  {
    slug: "techstars",
    name: "Techstars",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$120K ($20K + $100K convertible)",
    terms: "6% common",
    location: "Many cities globally",
    focus: "Broad, vertical programs (climate, health, defense, etc.)",
    deadline: "Rolling by program",
    applyUrl: "https://techstars.com/apply",
    website: "https://techstars.com",
    requirements: ["Full written app + deck", "Video + references"],
    timeEstimate: "5–7h",
    tags: ["founder", "generalist", "vertical"],
  },
  {
    slug: "pioneer",
    name: "Pioneer",
    type: "competition",
    stage: ["pre-idea", "pre-seed"],
    amount: "$100K (if you win Tournament)",
    terms: "Tournament → funding round",
    location: "Remote-first, optional SF trip",
    focus: "Solo founders, makers, researchers — any field",
    deadline: "Rolling weekly tournament",
    applyUrl: "https://pioneer.app",
    website: "https://pioneer.app",
    requirements: ["Weekly progress updates", "Peer-reviewed votes"],
    timeEstimate: "~1h/week over weeks",
    tags: ["solo-founder", "maker", "pre-idea", "research"],
  },
  {
    slug: "entrepreneur-first",
    name: "Entrepreneur First (EF)",
    type: "accelerator",
    stage: ["pre-idea"],
    amount: "~£80K / $100K",
    terms: "~10% equity",
    location: "London, Paris, Bangalore, NYC, SF",
    focus: "Technical talent without a cofounder or idea",
    deadline: "2 cohorts/year",
    applyUrl: "https://www.joinef.com/apply",
    website: "https://www.joinef.com",
    requirements: [
      "Long-form app (background, edge)",
      "Interview",
    ],
    timeEstimate: "3–5h",
    tags: ["pre-idea", "technical", "research", "founder"],
  },
  {
    slug: "on-deck-odx",
    name: "On Deck ODX",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$125K",
    terms: "Small equity",
    location: "Remote + SF IRL",
    focus: "Founders already building",
    deadline: "Rolling cohorts",
    applyUrl: "https://www.beondeck.com/odx",
    website: "https://www.beondeck.com",
    requirements: ["Short app + deck"],
    timeEstimate: "2–3h",
    tags: ["founder", "generalist"],
  },
  {
    slug: "hf0",
    name: "HF0 (Human Founders Fund) Residency",
    type: "residency",
    stage: ["pre-seed", "seed"],
    amount: "$500K (via separate SAFE)",
    terms: "No equity for the residency itself",
    location: "San Francisco · 12 weeks in-person",
    focus: "Repeat / technical founders shipping fast",
    deadline: "Rolling",
    applyUrl: "https://hf0.com",
    website: "https://hf0.com",
    requirements: ["Short app", "Technical background + idea"],
    timeEstimate: "1–2h",
    tags: ["technical", "founder", "ai"],
  },
  {
    slug: "neo-accelerator",
    name: "Neo Accelerator",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$625K (Ali Partovi's Neo)",
    terms: "SAFE",
    location: "San Francisco",
    focus: "Young technical founders",
    deadline: "Annual cohort",
    applyUrl: "https://neo.com/accelerator",
    website: "https://neo.com",
    requirements: ["Deck + team", "Code / demo"],
    timeEstimate: "3–4h",
    tags: ["technical", "founder", "young", "ai"],
  },
  {
    slug: "ai-grant",
    name: "AI Grant (Friedman & Gross)",
    type: "grant",
    stage: ["pre-seed"],
    amount: "$250K (cash) + $350K compute",
    terms: "Uncapped SAFE",
    location: "Remote; invited to SF events",
    focus: "AI-native products / research",
    deadline: "Multiple batches / year",
    applyUrl: "https://aigrant.com",
    website: "https://aigrant.com",
    requirements: [
      "Short written app",
      "Demo / GitHub / artifact",
    ],
    timeEstimate: "1–2h",
    tags: ["ai", "technical", "research", "founder"],
  },
  {
    slug: "z-fellows",
    name: "Z Fellows",
    type: "fellowship",
    stage: ["pre-idea", "pre-seed"],
    amount: "$10K grant + $1M commit to follow",
    terms: "No equity on the $10K",
    location: "SF 1-week sprint",
    focus: "Students / under-25 future founders",
    deadline: "Rolling cohorts",
    applyUrl: "https://zfellows.com/apply",
    website: "https://zfellows.com",
    requirements: ["Short app", "Evidence of agency"],
    timeEstimate: "45 min",
    tags: ["student", "young", "founder", "pre-idea"],
  },
  {
    slug: "thiel-fellowship",
    name: "Thiel Fellowship",
    type: "fellowship",
    stage: ["pre-idea", "pre-seed"],
    amount: "$100K / 2 years (no equity)",
    terms: "Must be under 22 and drop out / skip college",
    location: "Global",
    focus: "Exceptional young people building ambitious things",
    deadline: "Annual",
    applyUrl: "https://thielfellowship.org/apply",
    website: "https://thielfellowship.org",
    requirements: [
      "Long essays",
      "Evidence of exceptional work",
      "References",
    ],
    timeEstimate: "10–15h",
    tags: ["young", "pre-idea", "ambitious", "research"],
  },
  {
    slug: "emergent-ventures",
    name: "Emergent Ventures (Mercatus / Tyler Cowen)",
    type: "grant",
    stage: ["pre-idea", "any"],
    amount: "$5K–$100K+ grants (no equity)",
    terms: "Non-dilutive grant",
    location: "Global, remote",
    focus: "Ambitious ideas improving society",
    deadline: "Rolling",
    applyUrl: "https://emergentventures.com/apply",
    website: "https://emergentventures.com",
    requirements: [
      "Short proposal (what/why/how/budget)",
      "Bio / work samples",
    ],
    timeEstimate: "1–2h",
    tags: ["research", "grant", "non-dilutive", "ambitious"],
  },
  {
    slug: "atomic",
    name: "Atomic (studio)",
    type: "studio",
    stage: ["pre-idea", "pre-seed"],
    amount: "Salary + seed funding",
    terms: "Studio equity split",
    location: "SF / Miami / remote",
    focus: "Founders-in-residence co-building with Atomic",
    deadline: "Rolling",
    applyUrl: "https://atomic.vc/careers",
    website: "https://atomic.vc",
    requirements: ["Resume + founder history", "Call / on-site"],
    timeEstimate: "1–2h app + interviews",
    tags: ["pre-idea", "eir", "founder"],
  },
  {
    slug: "betaworks-camp",
    name: "Betaworks Camp",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$200K",
    terms: "Thematic 12-week camp",
    location: "New York",
    focus: "Themed cohorts (AI, voice, synthetic bio, etc.)",
    deadline: "Per theme",
    applyUrl: "https://www.betaworks.com/camp",
    website: "https://www.betaworks.com",
    requirements: ["Short app + deck"],
    timeEstimate: "2–3h",
    tags: ["ai", "founder", "themed"],
  },
  {
    slug: "conviction-embed",
    name: "Conviction Embed",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "$150K",
    terms: "SAFE + hands-on support",
    location: "San Francisco",
    focus: "AI-native companies pre-product",
    deadline: "Rolling",
    applyUrl: "https://conviction.com/embed",
    website: "https://conviction.com",
    requirements: ["Brief app + demo"],
    timeEstimate: "1–2h",
    tags: ["ai", "pre-seed", "founder"],
  },
  {
    slug: "khosla-ceo-in-residence",
    name: "Khosla Ventures CEO-in-Residence",
    type: "residency",
    stage: ["pre-idea", "pre-seed"],
    amount: "Salary + seed commit",
    terms: "Join KV to co-build",
    location: "Menlo Park",
    focus: "Repeat operators / deep-tech",
    deadline: "Rolling",
    applyUrl: "https://www.khoslaventures.com/careers/",
    website: "https://www.khoslaventures.com",
    requirements: ["Resume + pitch areas"],
    timeEstimate: "1h",
    tags: ["eir", "deep-tech", "founder"],
  },
  {
    slug: "sequoia-arc",
    name: "Sequoia Arc",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$1M",
    terms: "Cohort-based, ~8-week program",
    location: "San Francisco · London · Singapore",
    focus: "Ambitious early-stage founders",
    deadline: "Batches annually",
    applyUrl: "https://www.sequoiacap.com/arc/",
    website: "https://www.sequoiacap.com/arc/",
    requirements: ["Deck", "Team background", "Call"],
    timeEstimate: "3–5h",
    tags: ["founder", "ambitious", "generalist"],
  },
  {
    slug: "lightspeed-edge",
    name: "Lightspeed EDGE",
    type: "fellowship",
    stage: ["pre-idea", "pre-seed"],
    amount: "Mentorship + potential check",
    terms: "Varies",
    location: "US / India",
    focus: "Early founders",
    deadline: "Rolling",
    applyUrl: "https://lsvp.com/edge",
    website: "https://lsvp.com",
    requirements: ["App + background"],
    timeEstimate: "1–2h",
    tags: ["founder", "pre-idea"],
  },

  // ---------- Student + community fellowships ----------
  {
    slug: "dorm-room-fund",
    name: "Dorm Room Fund",
    type: "fellowship",
    stage: ["pre-seed"],
    amount: "$20K uncapped SAFE",
    terms: "Non-dilutive for fellow; check to company",
    location: "US",
    focus: "Student founders",
    deadline: "Rolling",
    applyUrl: "https://dormroomfund.com/apply",
    website: "https://dormroomfund.com",
    requirements: ["Student status", "Startup link/deck"],
    timeEstimate: "1h",
    tags: ["student", "pre-seed"],
  },
  {
    slug: "contrary-fellow",
    name: "Contrary Capital Fellowship",
    type: "fellowship",
    stage: ["pre-seed"],
    amount: "Up to $1M from Contrary",
    terms: "Standard",
    location: "US universities",
    focus: "Top student founders",
    deadline: "Rolling",
    applyUrl: "https://contrarycap.com/fellowship",
    website: "https://contrarycap.com",
    requirements: ["App + why you", "References"],
    timeEstimate: "2–3h",
    tags: ["student", "founder"],
  },
  {
    slug: "rough-draft-ventures",
    name: "Rough Draft Ventures (General Catalyst)",
    type: "fellowship",
    stage: ["pre-seed"],
    amount: "$25K–$100K",
    terms: "SAFE",
    location: "US",
    focus: "Student founders",
    deadline: "Rolling",
    applyUrl: "https://roughdraft.vc/apply",
    website: "https://roughdraft.vc",
    requirements: ["Team + deck"],
    timeEstimate: "1–2h",
    tags: ["student", "founder"],
  },
  {
    slug: "founders-inc",
    name: "Founders Inc.",
    type: "studio",
    stage: ["pre-idea", "pre-seed"],
    amount: "Varies",
    terms: "Studio / residency",
    location: "San Francisco · Fort Mason",
    focus: "Frontier tech builders (AI, robotics, BCI)",
    deadline: "Rolling",
    applyUrl: "https://f.inc",
    website: "https://f.inc",
    requirements: ["Brief app", "Show your work"],
    timeEstimate: "1h",
    tags: ["frontier", "ai", "hardware", "founder"],
  },
  {
    slug: "1517-fund",
    name: "1517 Fund",
    type: "fellowship",
    stage: ["pre-idea", "pre-seed"],
    amount: "$50K–$1M",
    terms: "Pre-idea grants + seed checks",
    location: "US",
    focus: "Under-22 / dropout founders + deep-tech",
    deadline: "Rolling",
    applyUrl: "https://www.1517fund.com/apply",
    website: "https://www.1517fund.com",
    requirements: ["App + demo"],
    timeEstimate: "1–2h",
    tags: ["young", "dropout", "founder"],
  },
  {
    slug: "kleiner-fellows",
    name: "Kleiner Perkins Fellows Program",
    type: "fellowship",
    stage: ["any"],
    amount: "Paid internship / fellowship",
    terms: "No equity",
    location: "Various portfolio cos",
    focus: "Students pre-career; product + engineering",
    deadline: "Annual",
    applyUrl: "https://fellows.kleinerperkins.com",
    website: "https://fellows.kleinerperkins.com",
    requirements: ["Resume + essays"],
    timeEstimate: "2–4h",
    tags: ["student", "engineer", "product"],
  },
  {
    slug: "fellows-fund",
    name: "Fellows Fund (Kai-Fu Lee)",
    type: "fellowship",
    stage: ["pre-seed", "seed"],
    amount: "Up to $500K",
    terms: "SAFE",
    location: "US + global",
    focus: "AI-first companies",
    deadline: "Rolling",
    applyUrl: "https://fellowsfund.ai",
    website: "https://fellowsfund.ai",
    requirements: ["Deck + demo"],
    timeEstimate: "1–2h",
    tags: ["ai", "founder"],
  },

  // ---------- AI / research-specific ----------
  {
    slug: "convergent-research",
    name: "Convergent Research FRO",
    type: "grant",
    stage: ["any"],
    amount: "$20M–$100M FROs (team-level)",
    terms: "Focused Research Org",
    location: "US",
    focus: "Large non-profit science projects",
    deadline: "Rolling proposals",
    applyUrl: "https://convergentresearch.org/contact",
    website: "https://convergentresearch.org",
    requirements: ["Detailed proposal", "Scientific team"],
    timeEstimate: "20+ hours",
    tags: ["research", "non-dilutive", "deep-tech"],
  },
  {
    slug: "openai-startup-fund",
    name: "OpenAI Startup Fund",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$5M–$20M",
    terms: "Equity + OpenAI credits",
    location: "Global",
    focus: "AI-forward companies using OpenAI",
    deadline: "Rolling",
    applyUrl: "https://openai.com/fund",
    website: "https://openai.com/fund",
    requirements: ["Deck", "Referral helps"],
    timeEstimate: "1–2h",
    tags: ["ai", "founder"],
  },
  {
    slug: "anthropic-credits",
    name: "Anthropic for Startups",
    type: "grant",
    stage: ["pre-seed", "seed", "series-a"],
    amount: "Up to $25K Anthropic API credits",
    terms: "Non-dilutive credits",
    location: "Global",
    focus: "Startups building with Claude",
    deadline: "Rolling",
    applyUrl: "https://anthropic.com/startups",
    website: "https://anthropic.com",
    requirements: ["Quick form", "Use case for Claude"],
    timeEstimate: "20 min",
    tags: ["ai", "credits", "founder"],
  },
  {
    slug: "aws-activate",
    name: "AWS Activate",
    type: "grant",
    stage: ["pre-seed", "seed", "series-a"],
    amount: "Up to $100K AWS credits",
    terms: "Cloud credits",
    location: "Global",
    focus: "Startups on AWS",
    deadline: "Rolling",
    applyUrl: "https://aws.amazon.com/activate/",
    website: "https://aws.amazon.com/activate/",
    requirements: ["Form + company info", "VC / accelerator referral for higher tiers"],
    timeEstimate: "30 min",
    tags: ["credits", "infra"],
  },
  {
    slug: "google-startups",
    name: "Google for Startups Cloud Program",
    type: "grant",
    stage: ["pre-seed", "seed", "series-a"],
    amount: "Up to $350K GCP credits",
    terms: "Cloud credits",
    location: "Global",
    focus: "Tech startups",
    deadline: "Rolling",
    applyUrl: "https://cloud.google.com/startup",
    website: "https://cloud.google.com/startup",
    requirements: ["Form + company info"],
    timeEstimate: "30 min",
    tags: ["credits", "infra"],
  },
  {
    slug: "microsoft-founders-hub",
    name: "Microsoft for Startups Founders Hub",
    type: "grant",
    stage: ["pre-seed", "seed"],
    amount: "Up to $150K Azure credits + OpenAI",
    terms: "Credits + support",
    location: "Global",
    focus: "Any tech startup",
    deadline: "Rolling",
    applyUrl: "https://startups.microsoft.com",
    website: "https://startups.microsoft.com",
    requirements: ["Form, 20 min"],
    timeEstimate: "30 min",
    tags: ["credits", "infra", "ai"],
  },
  {
    slug: "nvidia-inception",
    name: "NVIDIA Inception",
    type: "grant",
    stage: ["pre-seed", "seed", "series-a"],
    amount: "GPU credits + co-marketing",
    terms: "Program membership",
    location: "Global",
    focus: "AI / GPU-heavy startups",
    deadline: "Rolling",
    applyUrl: "https://www.nvidia.com/en-us/startups/",
    website: "https://www.nvidia.com/en-us/startups/",
    requirements: ["Company info form"],
    timeEstimate: "30 min",
    tags: ["credits", "ai", "hardware"],
  },

  // ---------- Deep tech / bio / climate ----------
  {
    slug: "activate",
    name: "Activate Fellowship",
    type: "fellowship",
    stage: ["pre-seed"],
    amount: "$100K stipend + $100K for research",
    terms: "2-year deep-tech fellowship",
    location: "Berkeley · Boston · NYC · Houston · DC",
    focus: "Hard-tech, climate, deep science",
    deadline: "Annual (spring)",
    applyUrl: "https://activate.org/fellowship",
    website: "https://activate.org",
    requirements: ["PhD-level technical depth", "Written app + references"],
    timeEstimate: "20+ hours",
    tags: ["deep-tech", "climate", "research"],
  },
  {
    slug: "breakout-labs",
    name: "Breakout Labs (Thiel Foundation)",
    type: "grant",
    stage: ["pre-seed"],
    amount: "Up to $500K",
    terms: "Non-dilutive / convertible",
    location: "US",
    focus: "Radical science commercialization",
    deadline: "Rolling",
    applyUrl: "https://breakoutlabs.org/apply",
    website: "https://breakoutlabs.org",
    requirements: ["Scientific team", "Long-form proposal"],
    timeEstimate: "10+ hours",
    tags: ["deep-tech", "research", "bio"],
  },
  {
    slug: "indiebio",
    name: "IndieBio (SOSV)",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$525K",
    terms: "Lab + program",
    location: "SF · NYC",
    focus: "Biotech + deep tech",
    deadline: "Batches / year",
    applyUrl: "https://indiebio.co/apply",
    website: "https://indiebio.co",
    requirements: ["Science + commercial plan"],
    timeEstimate: "5–7h",
    tags: ["bio", "deep-tech"],
  },
  {
    slug: "hax-hardtech",
    name: "HAX (SOSV)",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$250K–$500K",
    terms: "Hardware program",
    location: "Newark · Shenzhen",
    focus: "Industrial / robotics / hardware",
    deadline: "Rolling cohorts",
    applyUrl: "https://hax.co/apply",
    website: "https://hax.co",
    requirements: ["Demo / prototype"],
    timeEstimate: "5h",
    tags: ["hardware", "robotics", "industrial"],
  },
  {
    slug: "nucleate",
    name: "Nucleate",
    type: "fellowship",
    stage: ["pre-idea"],
    amount: "Programmatic support (non-dilutive)",
    terms: "Non-profit",
    location: "Global chapters",
    focus: "PhD / postdoc bio founders",
    deadline: "Annual",
    applyUrl: "https://nucleate.org",
    website: "https://nucleate.org",
    requirements: ["Academic + team"],
    timeEstimate: "4–6h",
    tags: ["bio", "research", "phd"],
  },
  {
    slug: "climate-builders",
    name: "Elemental Excelerator",
    type: "accelerator",
    stage: ["seed", "series-a"],
    amount: "Up to $500K (project + equity)",
    terms: "Grants + equity",
    location: "US",
    focus: "Climate tech",
    deadline: "Annual",
    applyUrl: "https://elementalexcelerator.com/apply",
    website: "https://elementalexcelerator.com",
    requirements: ["Pilot partner + tech"],
    timeEstimate: "10+ hours",
    tags: ["climate", "energy"],
  },
  {
    slug: "third-derivative",
    name: "Third Derivative",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "Funding + access",
    terms: "Program",
    location: "Global (climate)",
    focus: "Climate tech",
    deadline: "Annual",
    applyUrl: "https://third-derivative.org/apply",
    website: "https://third-derivative.org",
    requirements: ["Tech + market plan"],
    timeEstimate: "6–8h",
    tags: ["climate", "energy"],
  },

  // ---------- Defense / gov ----------
  {
    slug: "afwerx",
    name: "AFWERX Direct-to-Phase-II SBIR",
    type: "government",
    stage: ["pre-seed", "seed", "series-a"],
    amount: "Up to $1.7M",
    terms: "Non-dilutive",
    location: "US",
    focus: "Air Force dual-use tech",
    deadline: "Rolling + topic-based",
    applyUrl: "https://afwerx.com/open-topic",
    website: "https://afwerx.com",
    requirements: ["US entity", "Tech fit for AF problem"],
    timeEstimate: "15+ hours",
    tags: ["defense", "non-dilutive", "deep-tech"],
  },
  {
    slug: "diu",
    name: "Defense Innovation Unit (DIU) CSO",
    type: "government",
    stage: ["seed", "series-a"],
    amount: "Contract-based",
    terms: "Non-dilutive contract",
    location: "US",
    focus: "Commercial tech for DoD",
    deadline: "Per topic",
    applyUrl: "https://diu.mil/work-with-us",
    website: "https://diu.mil",
    requirements: ["White paper + pitch"],
    timeEstimate: "10–20h",
    tags: ["defense", "non-dilutive"],
  },
  {
    slug: "nsf-sbir",
    name: "NSF SBIR/STTR",
    type: "government",
    stage: ["pre-seed", "seed"],
    amount: "$275K (Phase I) → $1–2M (Phase II)",
    terms: "Non-dilutive grant",
    location: "US",
    focus: "Deep tech R&D",
    deadline: "3 solicitations / year",
    applyUrl: "https://seedfund.nsf.gov",
    website: "https://seedfund.nsf.gov",
    requirements: ["Project pitch → full proposal"],
    timeEstimate: "30–60h",
    tags: ["deep-tech", "non-dilutive", "research"],
  },
  {
    slug: "arpa-e-seed",
    name: "ARPA-E SEED",
    type: "government",
    stage: ["any"],
    amount: "Up to $1M (SEED) / up to $10M (OPEN)",
    terms: "Non-dilutive",
    location: "US",
    focus: "Energy breakthroughs",
    deadline: "Per FOA",
    applyUrl: "https://arpa-e.energy.gov/news-and-media/solicitations",
    website: "https://arpa-e.energy.gov",
    requirements: ["Concept paper + full proposal"],
    timeEstimate: "40+ hours",
    tags: ["energy", "climate", "research"],
  },
  {
    slug: "iarpa",
    name: "IARPA (Intelligence Advanced Research)",
    type: "government",
    stage: ["any"],
    amount: "Multi-year contracts",
    terms: "Non-dilutive",
    location: "US",
    focus: "High-risk intel research",
    deadline: "Per BAA",
    applyUrl: "https://iarpa.gov/engage-with-us/broad-agency-announcements",
    website: "https://iarpa.gov",
    requirements: ["Technical proposal"],
    timeEstimate: "40+ hours",
    tags: ["defense", "research", "non-dilutive"],
  },
  {
    slug: "darpa-baa",
    name: "DARPA Open BAAs",
    type: "government",
    stage: ["any"],
    amount: "Highly variable ($100K–$10M+)",
    terms: "Contract",
    location: "US",
    focus: "Breakthrough defense research",
    deadline: "Per topic",
    applyUrl: "https://sam.gov",
    website: "https://darpa.mil",
    requirements: ["Proposal matching topic"],
    timeEstimate: "40+ hours",
    tags: ["defense", "research", "non-dilutive"],
  },

  // ---------- Community + regional ----------
  {
    slug: "village-global",
    name: "Village Global Network Catalyst",
    type: "fellowship",
    stage: ["pre-idea", "pre-seed"],
    amount: "Small checks + network",
    terms: "Network program",
    location: "US + remote",
    focus: "Early founders",
    deadline: "Rolling",
    applyUrl: "https://villageglobal.vc",
    website: "https://villageglobal.vc",
    requirements: ["Brief app"],
    timeEstimate: "30 min",
    tags: ["founder", "pre-idea"],
  },
  {
    slug: "backstage-accelerator",
    name: "Backstage Accelerator",
    type: "accelerator",
    stage: ["pre-seed"],
    amount: "$100K",
    terms: "Equity",
    location: "LA / virtual",
    focus: "Underrepresented founders",
    deadline: "Cohorts",
    applyUrl: "https://backstage.capital",
    website: "https://backstage.capital",
    requirements: ["Short app"],
    timeEstimate: "1–2h",
    tags: ["founder", "diversity"],
  },
  {
    slug: "afore-fir",
    name: "Afore Capital Founder-in-Residence",
    type: "residency",
    stage: ["pre-idea"],
    amount: "$125K base + $1M seed commit",
    terms: "Standard",
    location: "SF",
    focus: "Exceptional solo founders",
    deadline: "Rolling",
    applyUrl: "https://afore.vc/fir",
    website: "https://afore.vc",
    requirements: ["Resume + thesis"],
    timeEstimate: "1h",
    tags: ["eir", "pre-idea", "founder"],
  },
  {
    slug: "compound-eir",
    name: "Compound EIR",
    type: "residency",
    stage: ["pre-idea"],
    amount: "Stipend + seed commit",
    terms: "Residency",
    location: "NYC / SF",
    focus: "Deep-tech founders",
    deadline: "Rolling",
    applyUrl: "https://compound.vc/careers",
    website: "https://compound.vc",
    requirements: ["Background"],
    timeEstimate: "1h",
    tags: ["deep-tech", "eir"],
  },
  {
    slug: "nfx-prehype",
    name: "NFX Fast (early check program)",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "Up to $1M",
    terms: "8-day decision",
    location: "SF",
    focus: "Networks-effects businesses",
    deadline: "Rolling",
    applyUrl: "https://nfx.com/fast",
    website: "https://nfx.com",
    requirements: ["Short memo"],
    timeEstimate: "1–2h",
    tags: ["founder", "fast-decision"],
  },
  {
    slug: "day-one-ventures-funded-not-fired",
    name: "Day One Ventures (Funded Not Fired)",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "$100K",
    terms: "SAFE",
    location: "Remote",
    focus: "Laid-off tech workers starting up",
    deadline: "Rolling when open",
    applyUrl: "https://dayoneventures.com",
    website: "https://dayoneventures.com",
    requirements: ["Short app"],
    timeEstimate: "30 min",
    tags: ["founder", "pre-seed"],
  },
  {
    slug: "alumni-ventures",
    name: "Alumni Ventures Group",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "Syndicate checks",
    terms: "Standard",
    location: "US",
    focus: "Generalist",
    deadline: "Rolling",
    applyUrl: "https://av.vc",
    website: "https://av.vc",
    requirements: ["Deck"],
    timeEstimate: "1h",
    tags: ["generalist"],
  },
  {
    slug: "india-accel-x",
    name: "Accel Atoms",
    type: "accelerator",
    stage: ["pre-seed"],
    amount: "Up to $1M",
    terms: "Program",
    location: "India",
    focus: "AI × India",
    deadline: "Cohorts",
    applyUrl: "https://atoms.accel.com",
    website: "https://atoms.accel.com",
    requirements: ["App + deck"],
    timeEstimate: "3h",
    tags: ["ai", "india"],
  },
  {
    slug: "matter",
    name: "MATTER Venture Partners",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$1M–$10M",
    terms: "Standard",
    location: "SF / JP",
    focus: "Hardware × AI",
    deadline: "Rolling",
    applyUrl: "https://matter.vc",
    website: "https://matter.vc",
    requirements: ["Deck"],
    timeEstimate: "1h",
    tags: ["hardware", "ai"],
  },
  {
    slug: "eleven-ventures",
    name: "Eleven Ventures",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "€50K–€200K",
    terms: "Program",
    location: "Sofia / CEE",
    focus: "CEE founders",
    deadline: "Cohorts",
    applyUrl: "https://eleven.vc",
    website: "https://eleven.vc",
    requirements: ["App + deck"],
    timeEstimate: "3h",
    tags: ["europe", "pre-seed"],
  },

  // ---------- Competitions / grants ----------
  {
    slug: "hustle-fund-angel-squad",
    name: "Hustle Fund Angel Squad",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "Syndicate access",
    terms: "Angel program",
    location: "Global",
    focus: "Angel / founder community",
    deadline: "Rolling",
    applyUrl: "https://angelsquad.hustlefund.vc",
    website: "https://hustlefund.vc",
    requirements: ["App"],
    timeEstimate: "30 min",
    tags: ["community", "angel"],
  },
  {
    slug: "long-journey",
    name: "Long Journey Ventures Fast Track",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "$250K",
    terms: "Quick decision",
    location: "SF",
    focus: "Weird, wonderful, AI",
    deadline: "Rolling",
    applyUrl: "https://longjourney.ventures",
    website: "https://longjourney.ventures",
    requirements: ["Brief memo"],
    timeEstimate: "1h",
    tags: ["ai", "weird", "fast-decision"],
  },
  {
    slug: "pear-garage",
    name: "Pear Garage",
    type: "fellowship",
    stage: ["pre-idea"],
    amount: "$250K commit",
    terms: "Pre-idea residency",
    location: "Palo Alto",
    focus: "Student / grad teams",
    deadline: "Rolling",
    applyUrl: "https://pear.vc/garage/",
    website: "https://pear.vc",
    requirements: ["App"],
    timeEstimate: "2h",
    tags: ["student", "pre-idea"],
  },
  {
    slug: "pear-competition",
    name: "Pear Competition",
    type: "competition",
    stage: ["pre-seed"],
    amount: "$250K commit",
    terms: "Competition prize",
    location: "US universities",
    focus: "Student / grad teams",
    deadline: "Annual",
    applyUrl: "https://pear.vc/competition",
    website: "https://pear.vc",
    requirements: ["Pitch"],
    timeEstimate: "5h",
    tags: ["student", "competition"],
  },
  {
    slug: "m12",
    name: "M12 (Microsoft's Venture Fund)",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$1M–$10M",
    terms: "Strategic",
    location: "Global",
    focus: "B2B / AI",
    deadline: "Rolling",
    applyUrl: "https://m12.vc",
    website: "https://m12.vc",
    requirements: ["Intro + deck"],
    timeEstimate: "1h",
    tags: ["ai", "b2b"],
  },
  {
    slug: "gv",
    name: "GV (Google Ventures)",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$1M–$50M",
    terms: "Standard",
    location: "Global",
    focus: "Generalist",
    deadline: "Rolling",
    applyUrl: "https://gv.com",
    website: "https://gv.com",
    requirements: ["Warm intro preferred"],
    timeEstimate: "1h",
    tags: ["generalist", "growth"],
  },
  {
    slug: "intel-capital",
    name: "Intel Capital",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$1M–$20M",
    terms: "Strategic",
    location: "Global",
    focus: "Deep tech / hardware",
    deadline: "Rolling",
    applyUrl: "https://intelcapital.com",
    website: "https://intelcapital.com",
    requirements: ["Pitch"],
    timeEstimate: "1h",
    tags: ["hardware", "deep-tech"],
  },
  {
    slug: "samsung-next",
    name: "Samsung Next",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$1M–$10M",
    terms: "Strategic",
    location: "Global",
    focus: "Frontier consumer / AI",
    deadline: "Rolling",
    applyUrl: "https://samsungnext.com",
    website: "https://samsungnext.com",
    requirements: ["Pitch"],
    timeEstimate: "1h",
    tags: ["ai", "consumer"],
  },
  {
    slug: "qualcomm-ventures",
    name: "Qualcomm Ventures",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$1M–$15M",
    terms: "Strategic",
    location: "Global",
    focus: "5G / AI / edge",
    deadline: "Rolling",
    applyUrl: "https://www.qualcomm.com/company/ventures",
    website: "https://www.qualcomm.com/company/ventures",
    requirements: ["Pitch"],
    timeEstimate: "1h",
    tags: ["ai", "hardware"],
  },

  // ---------- Starter credits / product-led programs ----------
  {
    slug: "stripe-atlas-perks",
    name: "Stripe Atlas + Perks",
    type: "grant",
    stage: ["pre-seed"],
    amount: "$50K+ of partner credits",
    terms: "Must use Atlas",
    location: "Global",
    focus: "Incorporate and get discounts",
    deadline: "Rolling",
    applyUrl: "https://stripe.com/atlas",
    website: "https://stripe.com/atlas",
    requirements: ["Form + $500 Atlas fee"],
    timeEstimate: "45 min",
    tags: ["credits", "incorporation"],
  },
  {
    slug: "mercury-raise",
    name: "Mercury Raise",
    type: "fund-program",
    stage: ["pre-seed", "seed"],
    amount: "Investor intros + community",
    terms: "Free program",
    location: "Global",
    focus: "Mercury customers",
    deadline: "Rolling",
    applyUrl: "https://mercury.com/raise",
    website: "https://mercury.com",
    requirements: ["Mercury account + deck"],
    timeEstimate: "1h",
    tags: ["pre-seed", "community"],
  },
  {
    slug: "brex-startup",
    name: "Brex for Startups Program",
    type: "grant",
    stage: ["pre-seed", "seed"],
    amount: "Credits + investor intros",
    terms: "Customer program",
    location: "US",
    focus: "Brex users",
    deadline: "Rolling",
    applyUrl: "https://brex.com/startups",
    website: "https://brex.com",
    requirements: ["Company info"],
    timeEstimate: "30 min",
    tags: ["credits", "pre-seed"],
  },
  {
    slug: "vercel-startups",
    name: "Vercel for Startups",
    type: "grant",
    stage: ["pre-seed", "seed"],
    amount: "$100K+ in Vercel credits",
    terms: "Startup program",
    location: "Global",
    focus: "Vercel customers",
    deadline: "Rolling",
    applyUrl: "https://vercel.com/startups",
    website: "https://vercel.com",
    requirements: ["Short form"],
    timeEstimate: "15 min",
    tags: ["credits", "infra"],
  },
  {
    slug: "replicate-credits",
    name: "Replicate credits for research",
    type: "grant",
    stage: ["any"],
    amount: "Free GPU inference credits",
    terms: "Researcher program",
    location: "Global",
    focus: "Open-source research",
    deadline: "Rolling",
    applyUrl: "https://replicate.com/research",
    website: "https://replicate.com",
    requirements: ["Research plan"],
    timeEstimate: "30 min",
    tags: ["ai", "research", "credits"],
  },
  {
    slug: "modal-credits",
    name: "Modal credits for startups",
    type: "grant",
    stage: ["pre-seed", "seed"],
    amount: "Free compute credits",
    terms: "Startup program",
    location: "Global",
    focus: "Modal customers",
    deadline: "Rolling",
    applyUrl: "https://modal.com/startups",
    website: "https://modal.com",
    requirements: ["Short form"],
    timeEstimate: "15 min",
    tags: ["ai", "credits", "infra"],
  },

  // ---------- More accelerators / European + Asia ----------
  {
    slug: "seedcamp",
    name: "Seedcamp",
    type: "accelerator",
    stage: ["pre-seed"],
    amount: "€300K",
    terms: "Equity",
    location: "London",
    focus: "European pre-seed",
    deadline: "Rolling",
    applyUrl: "https://seedcamp.com/apply",
    website: "https://seedcamp.com",
    requirements: ["Deck"],
    timeEstimate: "2h",
    tags: ["europe", "pre-seed"],
  },
  {
    slug: "startupbootcamp",
    name: "Startupbootcamp",
    type: "accelerator",
    stage: ["pre-seed"],
    amount: "€15K + perks",
    terms: "~8% equity",
    location: "Global",
    focus: "Vertical programs",
    deadline: "Per program",
    applyUrl: "https://startupbootcamp.org",
    website: "https://startupbootcamp.org",
    requirements: ["App + demo"],
    timeEstimate: "3h",
    tags: ["europe", "vertical"],
  },
  {
    slug: "massChallenge",
    name: "MassChallenge",
    type: "accelerator",
    stage: ["pre-seed"],
    amount: "Prize money up to $100K",
    terms: "Non-dilutive",
    location: "Boston / TX / IL / global",
    focus: "Any early-stage",
    deadline: "Annual",
    applyUrl: "https://masschallenge.org",
    website: "https://masschallenge.org",
    requirements: ["App"],
    timeEstimate: "4h",
    tags: ["non-dilutive", "generalist"],
  },
  {
    slug: "plug-and-play",
    name: "Plug and Play",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "Varies by vertical",
    terms: "Corporate innovation + demo days",
    location: "Sunnyvale + global",
    focus: "40+ verticals",
    deadline: "Per batch",
    applyUrl: "https://www.plugandplaytechcenter.com/startups/",
    website: "https://plugandplaytechcenter.com",
    requirements: ["Deck"],
    timeEstimate: "3h",
    tags: ["generalist", "vertical"],
  },
  {
    slug: "berkeley-skydeck",
    name: "Berkeley SkyDeck",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$200K",
    terms: "5% equity",
    location: "Berkeley",
    focus: "Berkeley-affiliated",
    deadline: "Batches",
    applyUrl: "https://skydeck.berkeley.edu",
    website: "https://skydeck.berkeley.edu",
    requirements: ["Berkeley ties + deck"],
    timeEstimate: "3h",
    tags: ["university", "generalist"],
  },
  {
    slug: "stanford-startx",
    name: "Stanford StartX",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "Non-dilutive + Stanford-StartX fund follow-on",
    terms: "Non-dilutive program",
    location: "Palo Alto",
    focus: "Stanford-affiliated",
    deadline: "Rolling",
    applyUrl: "https://startx.com/apply",
    website: "https://startx.com",
    requirements: ["Stanford affiliation", "Deck"],
    timeEstimate: "3h",
    tags: ["university", "stanford"],
  },
  {
    slug: "harvard-ilab",
    name: "Harvard iLab Venture Program",
    type: "fellowship",
    stage: ["pre-idea", "pre-seed"],
    amount: "Non-dilutive",
    terms: "Program + resources",
    location: "Cambridge",
    focus: "Harvard-affiliated",
    deadline: "Per term",
    applyUrl: "https://innovationlabs.harvard.edu",
    website: "https://innovationlabs.harvard.edu",
    requirements: ["Harvard affiliation"],
    timeEstimate: "2h",
    tags: ["university", "harvard"],
  },
  {
    slug: "mit-delta-v",
    name: "MIT delta v",
    type: "accelerator",
    stage: ["pre-seed"],
    amount: "~$25K stipend + resources",
    terms: "Non-dilutive",
    location: "Cambridge",
    focus: "MIT founders",
    deadline: "Annual (summer)",
    applyUrl: "https://entrepreneurship.mit.edu/programs/mit-delta-v",
    website: "https://entrepreneurship.mit.edu",
    requirements: ["MIT affiliation"],
    timeEstimate: "3h",
    tags: ["university", "mit"],
  },
  {
    slug: "mit-100k",
    name: "MIT $100K Competition",
    type: "competition",
    stage: ["pre-seed"],
    amount: "$100K prize",
    terms: "Non-dilutive",
    location: "Cambridge",
    focus: "MIT-led startups",
    deadline: "Annual",
    applyUrl: "https://www.mit100k.org",
    website: "https://www.mit100k.org",
    requirements: ["MIT affiliation", "Pitch"],
    timeEstimate: "5h",
    tags: ["university", "competition"],
  },
  {
    slug: "e14-fund",
    name: "The E14 Fund (MIT Media Lab)",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "$250K–$1M",
    terms: "Standard",
    location: "Cambridge",
    focus: "MIT Media Lab alumni",
    deadline: "Rolling",
    applyUrl: "https://e14fund.com",
    website: "https://e14fund.com",
    requirements: ["Media Lab affiliation"],
    timeEstimate: "1h",
    tags: ["mit", "deep-tech"],
  },
  {
    slug: "berkeleyblockchain",
    name: "Berkeley Blockchain Xcelerator",
    type: "accelerator",
    stage: ["pre-seed"],
    amount: "Non-dilutive",
    terms: "Program",
    location: "Berkeley",
    focus: "Web3 / blockchain",
    deadline: "Annual",
    applyUrl: "https://xcelerator.berkeley.edu",
    website: "https://xcelerator.berkeley.edu",
    requirements: ["Technical team"],
    timeEstimate: "2h",
    tags: ["web3"],
  },

  // ---------- Region-specific ----------
  {
    slug: "cdl",
    name: "Creative Destruction Lab (CDL)",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "Non-dilutive",
    terms: "Mentor-led program",
    location: "Toronto + 11 more",
    focus: "Deep tech (AI, quantum, health, space)",
    deadline: "Annual",
    applyUrl: "https://creativedestructionlab.com",
    website: "https://creativedestructionlab.com",
    requirements: ["Deep-tech team + deck"],
    timeEstimate: "5h",
    tags: ["deep-tech", "ai", "quantum"],
  },
  {
    slug: "ftx-like",
    name: "Pillar VC PillarVC Early Check",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "Up to $3M",
    terms: "Standard",
    location: "Boston",
    focus: "MIT / Harvard / Boston deep tech",
    deadline: "Rolling",
    applyUrl: "https://pillar.vc",
    website: "https://pillar.vc",
    requirements: ["Intro + deck"],
    timeEstimate: "1h",
    tags: ["boston", "deep-tech"],
  },
  {
    slug: "longjourney-sauce",
    name: "Pace Capital",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$2M–$10M",
    terms: "Standard",
    location: "NYC",
    focus: "Consumer + AI",
    deadline: "Rolling",
    applyUrl: "https://pace.capital",
    website: "https://pace.capital",
    requirements: ["Deck"],
    timeEstimate: "1h",
    tags: ["consumer", "ai"],
  },
  {
    slug: "ff-ventures",
    name: "First Round Capital First Step",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "$250K",
    terms: "Uncapped SAFE",
    location: "US",
    focus: "First-time founders",
    deadline: "Rolling",
    applyUrl: "https://firstround.com/firststep",
    website: "https://firstround.com",
    requirements: ["App + team"],
    timeEstimate: "1h",
    tags: ["pre-seed", "first-time"],
  },
  {
    slug: "uncork-first-check",
    name: "Uncork Capital First Check",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "Up to $2M",
    terms: "Standard",
    location: "Palo Alto",
    focus: "Seed-stage tech",
    deadline: "Rolling",
    applyUrl: "https://uncorkcapital.com",
    website: "https://uncorkcapital.com",
    requirements: ["Deck"],
    timeEstimate: "1h",
    tags: ["generalist", "seed"],
  },
  {
    slug: "initialized-labs",
    name: "Initialized Capital",
    type: "fund-program",
    stage: ["pre-seed", "seed"],
    amount: "$1M–$10M",
    terms: "Standard",
    location: "SF / NYC",
    focus: "Technical founders",
    deadline: "Rolling",
    applyUrl: "https://initialized.com",
    website: "https://initialized.com",
    requirements: ["Deck + intro"],
    timeEstimate: "1h",
    tags: ["technical", "seed"],
  },
  {
    slug: "greylock-edge",
    name: "Greylock Edge",
    type: "fellowship",
    stage: ["pre-idea", "pre-seed"],
    amount: "Mentorship + potential check",
    terms: "Program",
    location: "Menlo Park",
    focus: "Enterprise + AI",
    deadline: "Rolling",
    applyUrl: "https://greylock.com/edge",
    website: "https://greylock.com",
    requirements: ["App"],
    timeEstimate: "1h",
    tags: ["enterprise", "ai"],
  },
  {
    slug: "menlo-build",
    name: "Menlo Ventures Build",
    type: "fellowship",
    stage: ["pre-idea"],
    amount: "Commitments to build + fund",
    terms: "Program",
    location: "SF",
    focus: "Technical operators",
    deadline: "Rolling",
    applyUrl: "https://menlovc.com",
    website: "https://menlovc.com",
    requirements: ["App"],
    timeEstimate: "1h",
    tags: ["enterprise", "technical"],
  },

  // ---------- Community + syndicate ----------
  {
    slug: "bessemer-fellows",
    name: "Bessemer Fellows",
    type: "fellowship",
    stage: ["any"],
    amount: "Fellowship program",
    terms: "Non-dilutive",
    location: "Global",
    focus: "Student founders",
    deadline: "Annual",
    applyUrl: "https://bvp.com/fellows",
    website: "https://bvp.com",
    requirements: ["Student status + app"],
    timeEstimate: "2h",
    tags: ["student", "program"],
  },
  {
    slug: "character-labs",
    name: "Character Labs",
    type: "studio",
    stage: ["pre-idea", "pre-seed"],
    amount: "Design + capital",
    terms: "Studio",
    location: "Venice / SF",
    focus: "Consumer + design-led",
    deadline: "Rolling",
    applyUrl: "https://character.vc",
    website: "https://character.vc",
    requirements: ["Design-led product + team"],
    timeEstimate: "2h",
    tags: ["design", "consumer"],
  },
  {
    slug: "soundboks-nothing",
    name: "Nothing x Khosla Ventures Program",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "$150K",
    terms: "Standard",
    location: "London + Menlo Park",
    focus: "Consumer hardware + AI",
    deadline: "Rolling",
    applyUrl: "https://nothing.tech/pages/partners",
    website: "https://nothing.tech",
    requirements: ["App + deck"],
    timeEstimate: "2h",
    tags: ["hardware", "consumer"],
  },
  {
    slug: "fellows-weavers",
    name: "Weavers Fellowship (16z games / consumer-AI)",
    type: "fellowship",
    stage: ["pre-idea", "pre-seed"],
    amount: "Curated community + potential checks",
    terms: "Program",
    location: "SF",
    focus: "AI + consumer + games",
    deadline: "Annual",
    applyUrl: "https://weaversfellowship.com",
    website: "https://weaversfellowship.com",
    requirements: ["App + portfolio"],
    timeEstimate: "2h",
    tags: ["ai", "consumer", "games"],
  },
  {
    slug: "afore-alpha",
    name: "Afore Alpha",
    type: "competition",
    stage: ["pre-seed"],
    amount: "$1M commit to the winner",
    terms: "Competition",
    location: "SF",
    focus: "Pre-product founders",
    deadline: "Annual",
    applyUrl: "https://afore.vc/alpha",
    website: "https://afore.vc",
    requirements: ["Application + pitch"],
    timeEstimate: "3h",
    tags: ["pre-seed", "competition"],
  },
  {
    slug: "foundation-capital",
    name: "Foundation Capital",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$1M–$15M",
    terms: "Standard",
    location: "Menlo Park",
    focus: "Enterprise + AI",
    deadline: "Rolling",
    applyUrl: "https://foundationcap.com",
    website: "https://foundationcap.com",
    requirements: ["Deck"],
    timeEstimate: "1h",
    tags: ["enterprise", "ai"],
  },
  {
    slug: "accel-fast",
    name: "Accel Fast Track",
    type: "fund-program",
    stage: ["seed"],
    amount: "Up to $2M",
    terms: "SAFE",
    location: "SF / London",
    focus: "Fast seed decisions",
    deadline: "Rolling",
    applyUrl: "https://www.accel.com/fast-track",
    website: "https://www.accel.com",
    requirements: ["Short app"],
    timeEstimate: "30 min",
    tags: ["seed", "fast-decision"],
  },
  {
    slug: "craft-ventures",
    name: "Craft Ventures",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$1M–$20M",
    terms: "Standard",
    location: "SF",
    focus: "SaaS / AI / consumer",
    deadline: "Rolling",
    applyUrl: "https://www.craftventures.com",
    website: "https://www.craftventures.com",
    requirements: ["Deck"],
    timeEstimate: "1h",
    tags: ["saas", "ai"],
  },
  {
    slug: "gradient-ventures",
    name: "Gradient Ventures (Google)",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$1M–$15M",
    terms: "Strategic",
    location: "SF",
    focus: "AI-first",
    deadline: "Rolling",
    applyUrl: "https://www.gradient.com",
    website: "https://www.gradient.com",
    requirements: ["Deck"],
    timeEstimate: "1h",
    tags: ["ai", "strategic"],
  },
  {
    slug: "coatue-sprint",
    name: "Coatue Sprint (AI)",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "Bigger checks",
    terms: "Standard",
    location: "NYC / SF",
    focus: "AI",
    deadline: "Rolling",
    applyUrl: "https://www.coatue.com",
    website: "https://www.coatue.com",
    requirements: ["Intro + deck"],
    timeEstimate: "1h",
    tags: ["ai", "growth"],
  },
  {
    slug: "angellist-stack",
    name: "AngelList Stack",
    type: "grant",
    stage: ["pre-seed"],
    amount: "$1K+ credits across tools",
    terms: "Customer program",
    location: "Global",
    focus: "Startups using AngelList",
    deadline: "Rolling",
    applyUrl: "https://stack.angellist.com",
    website: "https://angellist.com",
    requirements: ["Form"],
    timeEstimate: "30 min",
    tags: ["credits"],
  },
  {
    slug: "ocean-protocol",
    name: "Ocean Protocol Grants (data DAOs)",
    type: "grant",
    stage: ["any"],
    amount: "$5K–$50K",
    terms: "Non-dilutive grant",
    location: "Global",
    focus: "Data × Web3 projects",
    deadline: "Rolling",
    applyUrl: "https://oceanprotocol.com/grants",
    website: "https://oceanprotocol.com",
    requirements: ["Proposal"],
    timeEstimate: "3–4h",
    tags: ["web3", "data"],
  },
  {
    slug: "github-sponsors",
    name: "GitHub Sponsors / Accelerator",
    type: "fellowship",
    stage: ["any"],
    amount: "Sponsor matching + accelerator",
    terms: "Community support",
    location: "Global",
    focus: "Open-source maintainers",
    deadline: "Rolling",
    applyUrl: "https://github.com/accelerator",
    website: "https://github.com/accelerator",
    requirements: ["Open-source project"],
    timeEstimate: "2h",
    tags: ["open-source", "community"],
  },
  {
    slug: "mozilla-builders",
    name: "Mozilla Builders",
    type: "accelerator",
    stage: ["pre-seed"],
    amount: "Up to $100K",
    terms: "Non-dilutive",
    location: "Global remote",
    focus: "Open-source AI tools",
    deadline: "Per theme",
    applyUrl: "https://builders.mozilla.org",
    website: "https://builders.mozilla.org",
    requirements: ["Open-source + AI"],
    timeEstimate: "4–6h",
    tags: ["open-source", "ai", "non-dilutive"],
  },
  {
    slug: "fastly-next-gen",
    name: "Cloudflare for Startups",
    type: "grant",
    stage: ["pre-seed", "seed"],
    amount: "Free Cloudflare + credits",
    terms: "Partner program",
    location: "Global",
    focus: "Cloudflare customers",
    deadline: "Rolling",
    applyUrl: "https://www.cloudflare.com/forstartups/",
    website: "https://www.cloudflare.com",
    requirements: ["Form"],
    timeEstimate: "20 min",
    tags: ["credits", "infra"],
  },
  {
    slug: "techstars-ai",
    name: "Techstars AI (various cities)",
    type: "accelerator",
    stage: ["pre-seed", "seed"],
    amount: "$120K",
    terms: "Standard Techstars",
    location: "Various",
    focus: "AI vertical cohorts",
    deadline: "Per city",
    applyUrl: "https://www.techstars.com/accelerators",
    website: "https://techstars.com",
    requirements: ["Standard Techstars app"],
    timeEstimate: "5–7h",
    tags: ["ai", "accelerator"],
  },
  {
    slug: "nsf-iCorps",
    name: "NSF I-Corps",
    type: "government",
    stage: ["pre-idea", "pre-seed"],
    amount: "$50K training + up to $500K follow-on",
    terms: "Non-dilutive",
    location: "US",
    focus: "University-affiliated founders",
    deadline: "Rolling by hub",
    applyUrl: "https://new.nsf.gov/funding/initiatives/i-corps",
    website: "https://new.nsf.gov",
    requirements: ["University affiliation", "Customer discovery"],
    timeEstimate: "7-week program"  ,
    tags: ["non-dilutive", "university"],
  },
  {
    slug: "catalyze-raise",
    name: "Catalyze Partners Raise",
    type: "fund-program",
    stage: ["pre-seed", "seed"],
    amount: "$100K–$1M",
    terms: "Standard",
    location: "NYC",
    focus: "B2B SaaS",
    deadline: "Rolling",
    applyUrl: "https://catalyze.com",
    website: "https://catalyze.com",
    requirements: ["Deck"],
    timeEstimate: "1h",
    tags: ["saas", "b2b"],
  },
  {
    slug: "unusual-ventures",
    name: "Unusual Academy",
    type: "fellowship",
    stage: ["pre-seed", "seed"],
    amount: "Programmatic",
    terms: "Non-dilutive",
    location: "Menlo Park",
    focus: "Unusual portfolio + select invites",
    deadline: "Annual",
    applyUrl: "https://www.unusual.vc/academy",
    website: "https://www.unusual.vc",
    requirements: ["Invite / application"],
    timeEstimate: "3h",
    tags: ["founder", "program"],
  },
  {
    slug: "gsf-founders-fellowship",
    name: "GSF Accelerator (India/Global)",
    type: "accelerator",
    stage: ["pre-seed"],
    amount: "$250K",
    terms: "Equity",
    location: "India / US",
    focus: "Global founders",
    deadline: "Cohorts",
    applyUrl: "https://gsfaccelerator.com",
    website: "https://gsfaccelerator.com",
    requirements: ["App"],
    timeEstimate: "3h",
    tags: ["global", "india"],
  },
  {
    slug: "tinyseed",
    name: "TinySeed",
    type: "accelerator",
    stage: ["pre-seed"],
    amount: "$160K–$240K",
    terms: "Remote 1-year program",
    location: "Remote",
    focus: "Bootstrapped SaaS",
    deadline: "Cohorts",
    applyUrl: "https://tinyseed.com",
    website: "https://tinyseed.com",
    requirements: ["Revenue or near it"],
    timeEstimate: "3h",
    tags: ["saas", "bootstrapped"],
  },
  {
    slug: "earlybird-x",
    name: "Earlybird EarlyX",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "€500K",
    terms: "Standard",
    location: "Berlin / London",
    focus: "Deep tech European",
    deadline: "Rolling",
    applyUrl: "https://earlybird.com",
    website: "https://earlybird.com",
    requirements: ["Intro + deck"],
    timeEstimate: "1h",
    tags: ["europe", "deep-tech"],
  },
  {
    slug: "speedinvest-pioneers",
    name: "Speedinvest Pioneers",
    type: "fund-program",
    stage: ["pre-seed"],
    amount: "€500K",
    terms: "Standard",
    location: "Vienna / London / Berlin",
    focus: "European pre-seed",
    deadline: "Rolling",
    applyUrl: "https://speedinvest.com",
    website: "https://speedinvest.com",
    requirements: ["Deck"],
    timeEstimate: "1h",
    tags: ["europe", "pre-seed"],
  },
  {
    slug: "kima-ventures",
    name: "Kima Ventures",
    type: "fund-program",
    stage: ["pre-seed", "seed"],
    amount: "€150K",
    terms: "Fast decisions",
    location: "Paris",
    focus: "Global pre-seed",
    deadline: "Rolling",
    applyUrl: "https://kimaventures.com",
    website: "https://kimaventures.com",
    requirements: ["Email + 2 slides"],
    timeEstimate: "30 min",
    tags: ["europe", "fast-decision"],
  },
  {
    slug: "sound-ventures-ai",
    name: "Sound Ventures AI Fund",
    type: "fund-program",
    stage: ["seed", "series-a"],
    amount: "$2M–$15M",
    terms: "Standard",
    location: "LA / SF",
    focus: "AI",
    deadline: "Rolling",
    applyUrl: "https://soundventures.com",
    website: "https://soundventures.com",
    requirements: ["Deck"],
    timeEstimate: "1h",
    tags: ["ai", "growth"],
  },
  {
    slug: "pilot-space",
    name: "Space Force SpaceWERX",
    type: "government",
    stage: ["pre-seed", "seed"],
    amount: "Up to $1.7M SBIR",
    terms: "Non-dilutive",
    location: "US",
    focus: "Space dual-use",
    deadline: "Rolling topics",
    applyUrl: "https://afwerx.com/divisions/spacewerx",
    website: "https://afwerx.com/divisions/spacewerx",
    requirements: ["US entity", "Tech fit"],
    timeEstimate: "15+ hours",
    tags: ["space", "defense", "non-dilutive"],
  },
  {
    slug: "dimes-ai-fellowship",
    name: "Cohere For AI Scholars",
    type: "fellowship",
    stage: ["any"],
    amount: "Research stipend + compute",
    terms: "Non-dilutive",
    location: "Global remote",
    focus: "ML research",
    deadline: "Annual",
    applyUrl: "https://cohere.com/research/scholars-program",
    website: "https://cohere.com/research",
    requirements: ["Research proposal"],
    timeEstimate: "10+ hours",
    tags: ["research", "ai"],
  },
  {
    slug: "openphil-ai-fellowship",
    name: "Open Philanthropy AI Fellowship",
    type: "fellowship",
    stage: ["any"],
    amount: "5-year PhD funding",
    terms: "Non-dilutive",
    location: "US / Global",
    focus: "ML PhD students in safety",
    deadline: "Annual",
    applyUrl: "https://www.openphilanthropy.org/focus/ai-fellowship/",
    website: "https://openphilanthropy.org",
    requirements: ["Admission to PhD program"],
    timeEstimate: "10+ hours",
    tags: ["research", "ai", "safety"],
  },
  {
    slug: "mats-alignment",
    name: "MATS (ML Alignment & Theory Scholars)",
    type: "fellowship",
    stage: ["any"],
    amount: "Stipend + mentorship",
    terms: "Non-dilutive",
    location: "Berkeley / London",
    focus: "AI safety research",
    deadline: "Per cohort",
    applyUrl: "https://matsprogram.org",
    website: "https://matsprogram.org",
    requirements: ["Application + research plan"],
    timeEstimate: "8+ hours",
    tags: ["research", "safety", "ai"],
  },
];

export const FUNDING_TYPES: { key: FundingType; label: string }[] = [
  { key: "accelerator", label: "Accelerators" },
  { key: "fellowship", label: "Fellowships" },
  { key: "studio", label: "Studios" },
  { key: "fund-program", label: "VC programs" },
  { key: "grant", label: "Grants / credits" },
  { key: "residency", label: "Residencies" },
  { key: "competition", label: "Competitions" },
  { key: "government", label: "Government" },
];
